apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample
  namespace: argo
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: chart
    repoURL: 'https://github.com/warapong-pj/mtl_assignment.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
